language: python
python:
  - "2.7"
  - "3.3"
  - "3.4"
  - "pypy"
matrix:
  allow_failures:
    # the pypy version in travis doesn't have cffi>=1.0
    - python: "pypy"
before_install:
  - git clone --depth=1 https://github.com/vstakhov/libucl.git
  - (cd libucl && ./autogen.sh && ./configure --prefix=/usr && make && sudo make install)
install: pip install .
script:
  - nosetests --verbose test
  - make doc
